"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/* tslint:disable */
require('./WebSearchTab.module.css');
var styles = {
    filePicker: 'filePicker_17f24cd8',
    tabsContainer: 'tabsContainer_17f24cd8',
    tabContainer: 'tabContainer_17f24cd8',
    nav: 'nav_17f24cd8',
    tabHeaderContainer: 'tabHeaderContainer_17f24cd8',
    breadcrumbNav: 'breadcrumbNav_17f24cd8',
    breadcrumbNavItem: 'breadcrumbNavItem_17f24cd8',
    tab: 'tab_17f24cd8',
    tabFiles: 'tabFiles_17f24cd8',
    scrollablePaneWrapper: 'scrollablePaneWrapper_17f24cd8',
    actionButtonsContainer: 'actionButtonsContainer_17f24cd8',
    actionButtons: 'actionButtons_17f24cd8',
    actionButton: 'actionButton_17f24cd8',
    tabHeader: 'tabHeader_17f24cd8',
    selectedTab: 'selectedTab_17f24cd8',
    header: 'header_17f24cd8',
    xlg: 'xlg_17f24cd8',
    xxlg: 'xxlg_17f24cd8',
    xxxlg: 'xxxlg_17f24cd8',
    xxxxlg: 'xxxxlg_17f24cd8',
    itemPickerTopBar: 'itemPickerTopBar_17f24cd8',
    commandBarNoChevron: 'commandBarNoChevron_17f24cd8',
    fileItem: 'fileItem_17f24cd8',
    folderItem: 'folderItem_17f24cd8',
    fileTypeIcon: 'fileTypeIcon_17f24cd8',
    fileTypeIconIcon: 'fileTypeIconIcon_17f24cd8',
    detailsListHeaderFileTypeIcon: 'detailsListHeaderFileTypeIcon_17f24cd8',
    iconColumnHeader: 'iconColumnHeader_17f24cd8',
    fileRow: 'fileRow_17f24cd8',
    folderRow: 'folderRow_17f24cd8',
    emptyFolder: 'emptyFolder_17f24cd8',
    emptyFolderImage: 'emptyFolderImage_17f24cd8',
    emptyFolderImageTag: 'emptyFolderImageTag_17f24cd8',
    emptyFolderTitle: 'emptyFolderTitle_17f24cd8',
    emptyFolderSubText: 'emptyFolderSubText_17f24cd8',
    emptyFolderMobile: 'emptyFolderMobile_17f24cd8',
    emptyFolderPc: 'emptyFolderPc_17f24cd8',
    emptyFolderIcon: 'emptyFolderIcon_17f24cd8',
    searchBoxContainer: 'searchBoxContainer_17f24cd8',
    searchBoxMedium: 'searchBoxMedium_17f24cd8',
    searchBox: 'searchBox_17f24cd8',
    dropdownContainer: 'dropdownContainer_17f24cd8',
    filterDropdown: 'filterDropdown_17f24cd8',
    filePickerFolderCardGrid: 'filePickerFolderCardGrid_17f24cd8',
    filePickerFolderCardTile: 'filePickerFolderCardTile_17f24cd8',
    filePickerFolderCardPadder: 'filePickerFolderCardPadder_17f24cd8',
    filePickerFolderCardSizer: 'filePickerFolderCardSizer_17f24cd8',
    filePickerFolderCardImage: 'filePickerFolderCardImage_17f24cd8',
    filePickerFolderCardLabel: 'filePickerFolderCardLabel_17f24cd8',
    bingGridListCell: 'bingGridListCell_17f24cd8',
    bingTile: 'bingTile_17f24cd8',
    bingTileContent: 'bingTileContent_17f24cd8',
    bingTileFrame: 'bingTileFrame_17f24cd8',
    bingTileCheckCircle: 'bingTileCheckCircle_17f24cd8',
    bingTileNamePlate: 'bingTileNamePlate_17f24cd8',
    isSelected: 'isSelected_17f24cd8',
    copyrightLabel: 'copyrightLabel_17f24cd8',
    noResultLabel: 'noResultLabel_17f24cd8',
    bingTileThumbnail: 'bingTileThumbnail_17f24cd8',
    bingGrildList: 'bingGrildList_17f24cd8',
};
exports.default = styles;
/* tslint:enable */ 

//# sourceMappingURL=WebSearchTab.module.scss.js.map
